### ISSUE TITLE
Unable to build on with aot in production mode on angular 4

### ISSUE THREAD

**Issue by karellodewijk** [johannesjo/angular2-promise-buttons#18]
Everything works fine in development mode, but when I try to build it in production mode, I get error.

Command: "ng build --watch --aot --target=production --base-href /app/"

`ERROR in Error: Metadata version mismatch for module C:/Users/pkali/Desktop/myonlineshareregister/frontend/node_modules/angular2-promise-buttons/dist/promise-btn-config.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (C:\Users\pkali\Desktop\myonlineshareregister\frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:25748:34)
    at StaticSymbolResolver._createSymbolsOf (C:\Users\pkali\Desktop\myonlineshareregister\frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:25536:46)
    at StaticSymbolResolver.getSymbolsOf (C:\Users\pkali\Desktop\myonlineshareregister\frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:25517:14)
    at C:\Users\pkali\Desktop\myonlineshareregister\frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:24376:30
    at Array.forEach (native)
    at extractProgramSymbols (C:\Users\pkali\Desktop\myonlineshareregister\frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:24375:79)
    at AotCompiler.analyzeModulesAsync (C:\Users\pkali\Desktop\myonlineshareregister\frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:23931:47)
    at CodeGenerator.codegen (C:\Users\pkali\Desktop\myonlineshareregister\frontend\node_modules\@angular\compiler-cli\src\codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (C:\Users\pkali\Desktop\myonlineshareregister\frontend\node_modules\@angular\compiler-cli\src\ngtools_api.js:73:30)
    at _donePromise.Promise.resolve.then (C:\Users\pkali\Desktop\myonlineshareregister\frontend\node_modules\@ngtools\webpack\src\plugin.js:386:44)`

**Comment by karellodewijk** [comment]
Ok locking the version to 1.1.0 did the trick, sorry for posting.

**Comment by johannesjo** [comment]
Thanks for reporting! This should work with the newest release as well. I will check as soon as I can!

**Comment by johannesjo** [comment]
I checked with version 2.0.0 and it also seems to work. Not sure what the issue is here. @karellodewijk 
would you be so kind to check with version 2.0.0 again?

**Comment by Lecha1** [comment]
This does not work with latest release of angular cli and angular! It gives the same error as reported above. And you would first say version of what? because version 2 etc does not make any sense in angular cli!

**Comment by maxkorz** [comment]
@Lecha1 could you please run `ng --version` and show us the output?

**Comment by Lecha1** [comment]
Angular CLI: 1.5.0
Node: 8.9.1
OS: win32 x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... tsc-wrapped

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.5.0
@angular/material: 2.0.0-beta.12
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.3.0
webpack: 3.8.1

**Comment by maxkorz** [comment]
@Lecha1 and package.json please?

**Comment by Lecha1** [comment]
{
  "name": "MyProject",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --aot",
    "code": "ng serve --ssl 1 --ssl-key \"C:\\code\\certs\\debug-cert\\server.key\" --ssl-cert \"C:\\code\\certs\\debug-cert\\server.crt\"",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.3.5",
    "@angular/cdk": "^2.0.0-beta.8",
    "@angular/common": "^4.3.5",
    "@angular/compiler": "^4.3.5",
    "@angular/compiler-cli": "^4.3.5",
    "@angular/core": "^4.3.5",
    "@angular/forms": "^4.3.5",
    "@angular/http": "^4.3.5",
    "@angular/material": "^2.0.0-beta.12",
    "@angular/platform-browser": "^4.3.5",
    "@angular/platform-browser-dynamic": "^4.3.5",
    "@angular/platform-server": "^4.3.5",
    "@angular/router": "^4.3.5",
    "angular-mat-datepicker": "0.0.2",
    "angular2-material-datepicker": "^0.5.0",
    "core-js": "^2.4.1",
    "enhanced-resolve": "^3.3.0",
    "jquery": "^3.2.1",
    "metismenu": "^2.7.0",
    "ng-lightning": "^2.0.1",
    "ng2-adal": "^1.0.0",
    "ng2-datepicker": "^2.1.3",
    "ng2-progressbar": "^1.3.0",
    "ngx-progressbar": "^2.0.4",
    "rxjs": "^5.1.0",
    "semantic-ui-css": "^2.2.12",
    "tinymce": "^4.7.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.5.0",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/jquery": "^3.2.11",
    "@types/metismenu": "^2.6.1",
    "@types/node": "~8.0.20",
    "codelyzer": "~3.1.2",
    "jasmine-core": "~2.7.0",
    "jasmine-spec-reporter": "~4.2.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.3.0",
    "tslint": "~5.6.0",
    "typescript": "^2.3.0"
  }
}

**Comment by maxkorz** [comment]
@Lecha1 use "Insert code" button to keep the formatting.

**Comment by Lecha1** [comment]
Ok I will do next time, did you find out whats the problem? Cheers Lecha

**Comment by maxkorz** [comment]
@Lecha1 I don't see any problem. Most likely an issue is in your configuration. I need you to update your posts using "Insert code" button to keep the formatting, so I could reproduce your environment on my PC.

**Comment by Lecha1** [comment]
Ok thanks for your time. if you want to reproduce something you can just copy and paste. It is not related to my configuration but related to the Angular cli's default configuration as it is clearly stated in the error shown. The other guy said he did change version of xxx to version xxx and it worked but as you he was not clear version what. As it is not clear in the error version of what index.d.ts file I even checked the local log file still nothing. So the problem is entirely in your app. Probably it worked with your configuration =) but if you want to release a stable version it cannot depend on what library I added or do not add. It has to be by default respecting all the libraries. Or may be I am not so experienced. Anyways you are not the first one who goes away from the topic there are the stuckoverflow guys as well the same as soon as it get to complicated the confidence drops drastically and human psychology takes its turn may be you moved right or left etc. Cheers Lecha

**Comment by maxkorz** [comment]
@Lecha1 I can't "just copy and paste" because you messed up the formatting, there's nothing to copy&paste:
```
"devDependencies": {
"": "^1.5.0",
"": "^4.0.0",
"": "^4.0.0",
"": "~2.5.53",
"": "~2.0.2",
"": "^3.2.11",
"": "^2.6.1",
"": "~8.0.20",
```

I'm working on several Angular 4 and 5 projects with Angular CLI and I don't experience the issue. I can't help you if I can't reproduce the environment that has the issue.

**Comment by Lecha1** [comment]
So I just edited it. You could say that from the beginning I am not expert on how things work here. You told me to give you the files and gave you. Cheers Lecha

**Comment by maxkorz** [comment]
@Lecha1 thank you, now I confirm the issue and can start working on it.
Meanwhile you can downgrade the plugin to the previous version:
`npm i --save angular2-promise-buttons@1.1.0`

**Comment by Lecha1** [comment]
Ok I did as you said and now it works, though the problem that I was trying to solve still remains. However your lib does its job as it promises. Thank you for your time and all the best! Cheers Lecha

**Comment by johannesjo** [comment]
@Lecha1 Thanks for reporting again! This is always very helpful!

**Comment by Lecha1** [comment]
No Problem, now I was even able to solve my problem using your promise button lib together with ng2-material. Thank you a lot and much appreciated and sorry for my unfair judgement before. Cheers Lecha
