### ISSUE TITLE
[feature] promiseForm

### ISSUE THREAD

**Issue by mits87** [johannesjo/angular2-promise-buttons#21]
Hi, 

first of all thank you for great plugin! I'm using your plugin mainly in my forms where spinner show when form is submitted. All works fine. I have an idea that you may like. When I'm submitting the form I would like show spinner on button and also block the form / add overlay etc. So maybe good idea will be add new directive eg. `promiseForm` which will add class for the form?

Thx

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting! I'll have to investigate this a little further and get back to you.

**Comment by johannesjo** [comment]
After investigating I found that this might be better implemented in a new directive. To disable a form completely, you need a <fieldset> wrapper element. You can see an example of this here: https://github.com/johannesjo/ng-fab-form/blob/master/src/ng-fab-form-directive-f.js#L17

**Comment by mits87** [comment]
I absolutely agree with you. Will you create the directive to your package?
