### ISSUE TITLE
Angular 6

### ISSUE THREAD

**Issue by mits87** [johannesjo/angular2-promise-buttons#22]
Hi, 

current version of angular2-promise-buttons is not compatible with Angular 6. Any plans to upgrade the package?

Thx

**Comment by johannesjo** [comment]
Thanks for reporting. Are there any errors showing up, when installing the package anyway?

**Comment by mits87** [comment]
Yes, there are a few errors like:

> ERROR in ./node_modules/angular2-promise-buttons/dist/promise-btn.directive.js
> Module not found: Error: Can't resolve 'rxjs/Observable' in '/app/node_modules/angular2-promise-buttons/dist'
> ERROR in ./node_modules/angular2-promise-buttons/dist/promise-btn.directive.js
> Module not found: Error: Can't resolve 'rxjs/Subscription' in '/app/node_modules/angular2-promise-buttons/dist'


Angular 6 uses a new version of RxJS. 
Look here: https://www.academind.com/learn/javascript/rxjs-6-what-changed/

**Comment by johannesjo** [comment]
I'll look into it (probably this weekend). Thank you!

**Comment by johannesjo** [comment]
I updated the package. Please let me know, if everything works as expected.

**Comment by mits87** [comment]
Now works! Thx
