### ISSUE TITLE
fix: package.json dependencies

### ISSUE THREAD

**Issue by thefliik** [johannesjo/angular2-promise-buttons#23]
Hey there,

I was just upgrading my app (which uses angular2-promise-buttons) to angular 6 and received a `angular2-promise-buttons@2.1.0" has incorrect peer dependency "@angular/core@6.0.1"` warning. Looking at the package.json, you have dependencies locked in for angular v6.0.1. Am I correct in thinking it should instead be `"@angular/core": "^6.0.1"` ? (the difference being `^`)

**Comment by johannesjo** [comment]
O thanks for reporting. That was not intentional. I'll provide a fix asap.

**Comment by thefliik** [comment]
Looks like npm still has the non-fixed version

**Comment by johannesjo** [comment]
Should be out now. Thanks for pointing it out!
