### ISSUE TITLE
Cannot resolve Angular2PromiseButtonModule dependency

### ISSUE THREAD

**Issue by husshd93** [johannesjo/angular2-promise-buttons#39]
After the update to 4.0.5, I can no longer import the module onto my project. It is missing the dist folder for some reason.
This used to be workign before the update, now it won't work even after reverting to 4.0.0

Also importing directly from the root folder will generate other errors. Pelase advise.

I also tried building it myself, I get these errors:
![image](https://user-images.githubusercontent.com/62701258/77644998-aabdbf80-6f6a-11ea-9266-82c6ccb10294.png)

**Comment by johannesjo** [comment]
Have you tried deleting your node_modules folder and doing a fresh install of all deps?

**Comment by husshd93** [comment]
Yes I have removed that foleder specifcally, and I have also removed th whole node_modules folder. same issue

**Comment by johannesjo** [comment]
> This used to be workign before the update, now it won't work even after reverting to 4.0.0
This strongly indicates that there is some other problem going on with your code, most likely unrelated to this module.

I tried and I am unable to reproduce any of the issues you're describing. How did you try building the lib?

**Comment by husshd93** [comment]
Thanks. I managed :D
