### ISSUE TITLE
promiseBtn breaks ngSubmit if handleCurrentBtnOnly is true

### ISSUE THREAD

**Issue by maxkorz** [johannesjo/angular2-promise-buttons#7]
Working version: http://plnkr.co/edit/3ZWAgkDc59O60n7mO8U6?p=preview
click **Simple Submit** and **promiseBtn submit**. You should see an Alert after both clicks.

Broken version: http://plnkr.co/edit/nL3Wj3ADkjcAKWXsWku6?p=preview
After I add handleCurrentBtnOnly option the **promiseBtn submit** doesn't work anymore

**Comment by johannesjo** [comment]
Thank you very much for reporting. I'll look into it.

**Comment by johannesjo** [comment]
Very very very weird. Somehow the model change detection is disabled when the button is disabled inside a form. No clue why, but setting a timeout seems to help. Should be available in the current release.
