### ISSUE TITLE
Peer dependency issues with npm 7

### ISSUE THREAD

**Issue by Bykiev** [johannesjo/angular2-promise-buttons#73]
## :ghost: Brief Description

Npm v7: 

>  Could not resolve dependency:
> npm ERR! peer @angular/common@"^9.0.4" from angular2-promise-buttons@5.0.2
> npm ERR! node_modules/angular2-promise-buttons
> npm ERR!   angular2-promise-buttons@"^5.0.2" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

## :pancakes: Action version

v5.0.2

## :tophat: workflow configuration

Angular 11.2.14

## Steps To Reproduce

1. create Angular 11 app
2. `npm install angular2-promise-buttons --save`
3. wait a bit

## :police_car: Expected behavior

Warning shold be avoided

## :heavy_plus_sign: Additional context

The issue is caused by changed behavior of npm, now it installs peer dependencies. Please, change peerDependencies in [package.json](https://github.com/johannesjo/angular2-promise-buttons/blob/5da9c5fc8e9401c0a1384140a28803a022bffb93/projects/angular2-promise-buttons/package.json#L22-L25) file as to this:

```
 "@angular/core": ">=9.0.4",
  "@angular/common": ">=9.0.4",
```

**Comment by johannesjo** [comment]
Thank you!
