### ISSUE TITLE
The project won't build

### ISSUE THREAD

**Issue by maxkorz** [johannesjo/angular2-promise-buttons#8]
Hi. I'd like to contribute to this project but the building and testing tasks fail to execute.

ng test:
```
16 07 2017 01:30:08.112:WARN [karma]: No captured browser, open http://localhost:9876/
16 07 2017 01:30:08.119:INFO [karma]: Karma v1.4.1 server started at http://0.0.0.0:9876/
16 07 2017 01:30:08.120:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
16 07 2017 01:30:08.124:INFO [launcher]: Starting browser PhantomJS
16 07 2017 01:30:12.066:WARN [karma]: No captured browser, open http://localhost:9876/
16 07 2017 01:30:12.487:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Connected on socket KHmwP3lvXV5fGRFTAAAA with id 78684792
PhantomJS 2.1.1 (Windows 7 0.0.0): Executed 0 of 0 ERROR (0.002 secs / 0 secs)
```

npm run demo.build
```
> angular2-promise-buttons@1.0.8 demo.build C:\Work\angular2-promise-buttons
> ng build -prod --aot

Hash: 9c7945ca1c326e2bbeed
Time: 7112ms
chunk    {0} main.b8df572cc9013c42172c.bundle.js (main) 30.6 kB {2} [initial] [rendered]
chunk    {1} styles.7a0d398e75d4b4028359.bundle.css (styles) 69 bytes {3} [initial] [rendered]
chunk    {2} vendor.a99ac1ef4f81470bcc09.bundle.js (vendor) 1.23 MB [initial] [rendered]
chunk    {3} inline.db7219f7e0829c1208de.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in C:/Work/angular2-promise-buttons/demo/src/$$_gendir/src/angular2-promise-buttons.module.ngfactory.ts (10,21): Cannot find module './angular2-promise-buttons.module'.
```

npm version: 5.3.0
node version: v8.1.3
OS: Windows 7

Do you have any idea what's wrong?
All I did is
```
npm install
npm install -g @angular/cli
```
Are there any additional steps?

**Comment by maxkorz** [comment]
https://github.com/johannesjo/angular2-promise-buttons/commit/a144795af26ffce894e7174e965f73101f297569 look like this is the issue.
I created a symlink with Windows tool and everything works.

But I don't think that symlink is a real solution to this, as it makes the development process harder for windows users.

I'll close this issue, but I hope a better solution will come up.

**Comment by johannesjo** [comment]
Thanks for reporting. I should probably add this to the docs.

**Comment by maxkorz** [comment]
@johannesjo hi. I think you should create a [CONTRIBUTING file](https://github.com/blog/1184-contributing-guidelines) in the root directory. It should explain how to build the project, how to run the tests, how to avoid issues like this one.
